services:
  - type: web
    name: dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port 10000 --server.headless true"
    envVars:
      - key: PORT
        value: 10000

  - type: worker
    name: discord-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
